version: "1"
services:
  app:
   container_name: olivia-api-gatweay
   restart: always
   build: .
   ports:
     - "8080:8080"
   links:
   - mongo
   environment:
   - DB_URI=mongodb://mongo:27017/olivia
  mongo:
   container_name: mongo
   image: mongo
   ports:
   - "27017:27017"