# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy de Olivia API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    environment: production
    strategy:
      matrix:
        node-version: [18.x]


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: creating .env file
      run: |
          touch .env
          echo DB_URI=${{secrets.DB_URI}} >> .env
          echo JWT_SECRET=${{secrets.JWT_SECRET}} >> .env
          echo BUCKET_NAME=${{secrets.BUCKET_NAME}} >> .env
          echo BUCKET_REGION=${{secrets.BUCKET_REGION}} >> .env
          echo PUBLIC_KEY=${{secrets.PUBLIC_KEY}} >> .env
          echo SECRET_KEY=${{secrets.SECRET_KEY}} >> .env
          echo PORT=8080 >> .env
          cat .env
    - run: npm i
    - run: npm run build 
    - run: pm2 restart olivia-api
